<<<<<<< HEAD
spring.application.name=LT-WEB

spring.datasource.url=jdbc:mysql://localhost:3306/baoweb2
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
=======
spring.application.name=web2
>>>>>>> 8a6510615af917af4b5574950e58fd7242fb67e0
